#!/bin/bash

#----------------------------------------------------------------------------------------------
#
#      MAIN
#
#----------------------------------------------------------------------------------------------

# declarations of MUST HAVE globals
PROGRAM_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
PROGRAM_NAME="$(basename "${BASH_SOURCE[0]}")"
LOGFILE="$(pwd)/${PROGRAM_NAME}.log"

declare -r LIB_NAME='confluence-utilities'
declare -A OPTS=()
declare -a ARGS=()


# load our libraries
declare -r loader="${PROGRAM_DIR}/bashlib/appenv.bashlib"
if [ ! -e "$loader" ]; then
    echo 'Unable to load libraries' >&2
    exit 1
fi
source "$loader"
appenv.initialize "$@"

# our main script
declare -i status=0
{
    if [ "${OPTS['user']:-}" ]; then
        export _CONFLUENCE_USER="${OPTS['user']}"
        export _CONFLUENCE_CREDENTIALS=$(credentials.get confluence)
    fi

    # regular output
    "${OPTS['cmd']}" ${OPTS['oper']:-} "${ARGS[@]:-}" && status=$? || status=$?

} 2>&1 | tee "$LOGFILE"

exit $status
