#!/bin/bash

#----------------------------------------------------------------------------------------------
#
#      MAIN
#
#----------------------------------------------------------------------------------------------

# declarations of MUST HAVE globals
declare -r PROGRAM_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
declare -r PROGRAM_NAME="$(basename "${BASH_SOURCE[0]}")"
declare -r LOGFILE="$(pwd)/${PROGRAM_NAME}.log"
declare -r LIB_NAME='deploy'
declare -A OPTS=(['cmd']='deploy.restart' ['base']="$(pwd)")
declare -a ARGS=()

declare -ax COMPLETION_MSG SKIP_WAIT


# load our libraries
declare -r loader="${PROGRAM_DIR}/bashlib/appenv.bashlib"
if [ ! -e "$loader" ]; then
    echo 'Unable to load libraries' >&2
    exit 1
fi
source "$loader"
appenv.initialize "$@"


# our main script
declare -i status=0
{
    deploy.initGlobals
    appenv.showArgs

    # need docker-compose.yml to stop/remove running containers
    deploy.fixWorkspaceYaml

    # regular output
    "${OPTS['cmd']}" "${ARGS[@]}" && status=$? || status=$? 

} 2>&1 | tee "$LOGFILE"

exit $status 
