#!/bin/bash

#----------------------------------------------------------------------------------------------
#
#      MAIN
#
#----------------------------------------------------------------------------------------------

# declarations of MUST HAVE globals
PROGRAM_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
PROGRAM_NAME="$(basename "${BASH_SOURCE[0]}")"
LOGFILE="$(pwd)/${PROGRAM_NAME}.log"

declare -r LIB_NAME='docker-utilities'
declare -A OPTS=()
declare -a ARGS=()
declare -A IMAGES_TO_DELETE=()
declare -A REPO_DIGESTS=()

# load our libraries
declare -r loader="${PROGRAM_DIR}/bashlib/appenv.bashlib"
if [ ! -e "$loader" ]; then
    echo 'Unable to load libraries' >&2
    exit 1
fi
source "$loader"
appenv.initialize "$@"

# our main script
declare -i status=0
{
    if [ "${OPTS['isrunning']:-}" ]; then
        "${OPTS['isrunning']}" || trap.die 'Docker is not running'
    fi

    if [ "${OPTS['user']:-}" ]; then
        export _REGISTRY_USER="${OPTS['user']}"
        export _REGISTRY_CREDENTIALS=$(credentials.get registry)
    fi
 
    # regular output
    if [ "${#ARGS[*]}" -gt 0 ]; then
        "${OPTS['cmd']}" ${OPTS['oper']:-} "${ARGS[@]:-}" && status=$? || status=$?
    else
        "${OPTS['cmd']}" ${OPTS['oper']:-} && status=$? || status=$?
    fi
    exit $status 

} 2>&1 | tee "$LOGFILE"
